// teamTasksApi.js — the team's markdown task tracker, read LIVE from disk.
//
//   GET /api/cockpit/team-tasks
//       { available, generatedAt, sources: [ { id, label, available, counts,
//         closedTruncated, items } ] }
//
// WHY LIVE, NOT THE mypka.db MIRROR
// Every other Team-Knowledge surface in the cockpit (workstreams / sops /
// guidelines / session logs) reads the SQLite mirror. Tasks deliberately do not.
// The mirror is regenerated by scripts/regen-mypka-db.py, which runs from
// start-cockpit.command — but this machine starts the server through a LaunchAgent
// that execs server.js directly, so the regen does NOT run on boot. Measured on
// 2026-08-19: mypka.db was written 2026-08-18 21:39 while the task index had been
// rebuilt 2026-08-19 08:00. Task status changes several times a day; a task board
// that is half a day stale is worse than none, because it is wrong without saying
// so. Reading the folder costs a few milliseconds and is never stale.
// (Full reasoning: Deliverables/2026-08-19-teamtaken-in-cockpit-dashboard-design.md)
//
// POSTURE
//   * READ-ONLY. Nothing here writes, moves, or touches a task file. Markdown
//     stays canonical; task lifecycle belongs to the task SOPs.
//   * NEVER THROWS. An unreadable file costs THAT ROW, never the response. A
//     missing status folder costs that folder. A missing source root marks that
//     one source unavailable and the others still render.
//   * JAILED. Every resolved path is checked against its source root before it is
//     read, and symlinks are skipped outright — the reader can never be walked out
//     of the configured folder.
//   * Rides the standard `safe(handler)` envelope, so it inherits the SAME
//     loopback/PIN/CSRF read-gate as every other /api/cockpit route.
//
// WHICH FOLDERS: see taskSources.js. That file is the extension seam — adding
// PKM/Tasks/ later is one entry there, not a change here.
import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT } from './repoRoot.js';
import { TASK_SOURCES } from './taskSources.js';
import { parseTaskFrontmatter } from './taskFrontmatter.js';

// Depth guard for the recursive status folders (done/YYYY/MM/ is depth 2). Cheap
// insurance against a pathological tree; never hit in normal use.
const MAX_DEPTH = 4;

// Closed statuses accumulate forever. Counts always reflect everything on disk,
// but the ITEM list for done/cancelled is capped at the newest N so the payload
// stays bounded as the archive grows. `closedTruncated` tells the client when it
// is looking at a capped list rather than the whole archive.
const CLOSED_ITEM_CAP = 20;
const CLOSED_STATUSES = new Set(['done', 'cancelled']);

const SUMMARY_CHARS = 220;

// ---- filesystem helpers ------------------------------------------------------

// True iff `abs` really sits under `base`. Both must already be resolved.
function containedIn(base, abs) {
  const rel = path.relative(base, abs);
  return rel !== '' && !rel.startsWith('..') && !path.isAbsolute(rel);
}

// Collect files under `dir`. Symlinks (files AND directories) are skipped so the
// walk can never leave the jail through a link. Unreadable directories are
// skipped silently — an absent status folder is a normal state, not an error.
function collectFiles(dir, recursive, base, out, depth = 0) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const abs = path.resolve(dir, entry.name);
    if (!containedIn(base, abs)) continue;
    if (entry.isSymbolicLink()) continue;
    if (entry.isDirectory()) {
      if (recursive && depth < MAX_DEPTH) collectFiles(abs, recursive, base, out, depth + 1);
      continue;
    }
    if (entry.isFile()) out.push(abs);
  }
}

// ---- shaping -----------------------------------------------------------------

// First real prose paragraph of the body — the same technique the governance-doc
// mirror uses for `summary`. Skips the H1 and any heading/bullet/table/quote line,
// so what surfaces is the opening of "## What this is" rather than a heading.
function summaryFromBody(body) {
  if (!body) return null;
  for (const para of String(body).split(/\n\s*\n/)) {
    const p = para.trim();
    if (!p) continue;
    const first = p.split('\n')[0].trimStart();
    if (/^(#|-|\*|\||>|_\()/.test(first)) continue;
    const flat = p.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2')
      .replace(/\[\[([^\]]+)\]\]/g, '$1')
      .replace(/[*_`]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
    if (!flat) continue;
    if (flat.length <= SUMMARY_CHARS) return flat;
    const cut = flat.slice(0, SUMMARY_CHARS);
    const lastSpace = cut.lastIndexOf(' ');
    return `${(lastSpace > 80 ? cut.slice(0, lastSpace) : cut).trim()}…`;
  }
  return null;
}

function asText(v) {
  if (v === null || v === undefined) return null;
  const s = String(v).trim();
  return s === '' ? null : s;
}

// priority is 1 (urgent) .. 4 (low) per the task template. Anything else -> null,
// so the view can render "no priority" instead of inventing one.
function asPriority(v) {
  const n = Number(v);
  return Number.isInteger(n) && n >= 1 && n <= 4 ? n : null;
}

function asTags(v) {
  if (!Array.isArray(v)) return [];
  return v.map((x) => asText(x)).filter((x) => x !== null);
}

function shape(abs, fm, body, statusDir, sourceRootAbs) {
  const stem = path.basename(abs, '.md');
  const blockedReason = asText(fm.blocked_reason);
  return {
    // slug = filename stem: unique across the tree, stable React key, and the
    // exact token the [[wikilinks]] in INDEX.md use.
    slug: stem,
    id: asText(fm.id) || stem,
    title: asText(fm.title) || stem,
    // The FOLDER is authoritative over the file's own `status:` field. That is
    // SOP-rebuild-task-index's drift rule ("the folder wins"), and it means this
    // view can never disagree with where a task physically lives.
    status: statusDir.status,
    statusFieldDrift: asText(fm.status) !== null && asText(fm.status) !== statusDir.status,
    assignee: asText(fm.assignee) || 'unassigned',
    priority: asPriority(fm.priority),
    due: asText(fm.due),
    created: asText(fm.created),
    updated: asText(fm.updated),
    createdBy: asText(fm.created_by),
    blocked: blockedReason !== null,
    blockedReason,
    tags: asTags(fm.tags),
    summary: summaryFromBody(body),
    filePath: path.relative(REPO_ROOT, abs).split(path.sep).join('/'),
    // Kept for the source root it came from, so a multi-source client can group
    // without re-deriving it from the path.
    sourceRoot: path.relative(REPO_ROOT, sourceRootAbs).split(path.sep).join('/'),
  };
}

// Within one status: priority first (nulls last), then oldest-created first for
// open work (the most-stale item reads at the top), newest first for closed work.
function sortItems(items, status) {
  const closed = CLOSED_STATUSES.has(status);
  return items.sort((a, b) => {
    if (!closed) {
      const pa = a.priority ?? 99;
      const pb = b.priority ?? 99;
      if (pa !== pb) return pa - pb;
    }
    const da = a.updated || a.created || '';
    const db = b.updated || b.created || '';
    if (da === db) return a.slug.localeCompare(b.slug);
    return closed ? db.localeCompare(da) : da.localeCompare(db);
  });
}

// ---- the reader --------------------------------------------------------------

function readSource(source) {
  const rootAbs = path.resolve(REPO_ROOT, source.root);
  let rootOk = false;
  try {
    rootOk = fs.statSync(rootAbs).isDirectory();
  } catch {
    rootOk = false;
  }
  if (!rootOk) {
    return {
      id: source.id,
      label: source.label,
      root: source.root,
      available: false,
      counts: {},
      closedTruncated: false,
      items: [],
    };
  }

  const items = [];
  const counts = {};
  let closedTruncated = false;

  for (const statusDir of source.statusDirs) {
    const dirAbs = path.resolve(rootAbs, statusDir.dir);
    if (!containedIn(rootAbs, dirAbs)) continue; // configuration guard

    const files = [];
    collectFiles(dirAbs, !!statusDir.recursive, rootAbs, files);

    const rows = [];
    for (const abs of files) {
      if (!source.filePattern.test(path.basename(abs))) continue;
      try {
        const raw = fs.readFileSync(abs, 'utf8');
        const { fm, body } = parseTaskFrontmatter(raw);
        rows.push(shape(abs, fm, body, statusDir, rootAbs));
      } catch {
        // One unreadable file costs one row, never the response. Deliberately
        // silent: a per-file console line would be noise on every poll.
      }
    }

    // counts ALWAYS reflect everything found on disk, even when the item list
    // below is capped.
    counts[statusDir.status] = rows.length;

    sortItems(rows, statusDir.status);
    if (CLOSED_STATUSES.has(statusDir.status) && rows.length > CLOSED_ITEM_CAP) {
      closedTruncated = true;
      items.push(...rows.slice(0, CLOSED_ITEM_CAP));
    } else {
      items.push(...rows);
    }
  }

  // Derived roll-ups the client would otherwise have to compute itself.
  counts.blocked = items.filter((i) => i.blocked).length;
  counts.total = Object.entries(counts)
    .filter(([k]) => k !== 'blocked' && k !== 'total')
    .reduce((sum, [, v]) => sum + v, 0);

  return {
    id: source.id,
    label: source.label,
    root: source.root,
    available: true,
    counts,
    closedTruncated,
    items,
  };
}

/**
 * readAllSources() -> the full envelope. Never throws.
 *
 * The envelope carries an ARRAY of sources even though only one is configured
 * today. That is the scope-B contract: wiring PKM/Tasks/ in later is an entry in
 * taskSources.js, with no change to this shape, the route, or the client.
 */
export function readAllSources() {
  const sources = [];
  for (const source of TASK_SOURCES) {
    try {
      sources.push(readSource(source));
    } catch {
      sources.push({
        id: source.id,
        label: source.label,
        root: source.root,
        available: false,
        counts: {},
        closedTruncated: false,
        items: [],
      });
    }
  }
  return {
    available: sources.some((s) => s.available),
    generatedAt: new Date().toISOString(),
    sources,
  };
}

export function registerTeamTasksRoutes(app, { safe }) {
  app.get('/api/cockpit/team-tasks', safe(() => readAllSources()));
}

export default registerTeamTasksRoutes;
